yarnPath: .yarn/releases/yarn-3.2.1.cjs
nodeLinker: node-modules
packageExtensions:
  "react-dev-utils@12.0.1":
    peerDependencies:
      typescript: ">=2.7"
      webpack: ">=4"

  "eslint-config-react-app@7.0.1":
    dependencies:
      "@babel/plugin-syntax-flow": "^7.14.5"
      "@babel/plugin-transform-react-jsx": "^7.14.9"
